OCA/oca-addons-repo-template

- {{ _copier_conf.answers_file }}.jinja
This should help PSCs that have wrong expectations about how Copier works to avoid update problems, as seen in #6.
> Warn more about manual updates to answers file

- .pre-commit-config.yaml.jinja
The default available on travis is too old.
fixes #15
> Set language_version for prettier

- .prettierrc.yml
This will make XML files be less pretty, but also less surprising.
Fix #34.
> Use strict mode in prettier xml plugin

- .pre-commit-config.yaml.jinja
- copier.yml
Generate `requirements.txt` from manifest python `external_dependencies` and `setup.py` overrides if any.
Closes #23
> Add setuptools-odoo-get-requirements

- .pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml
The prettier/prettier hook is broken and incompatible with pre-commit 2.8+. Switch to prettier/pre-commit.
See also https://github.com/pre-commit/pre-commit/issues/1674
> Switch to prettier/pre-commit repo

- version-specific/13.0/.pre-commit-config.yaml
This is apparently necessary for the development status checks to work correctly.
So let's align the pylint and pylint-odoo version with the 14.0 branch.
> Upgrade pylint-odoo for 13.0

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml
I hope https://github.com/prettier/pre-commit/commit/d2e9f0ce87ad6dd21deb8c48e81f92401af92988 is the last chapter of this prettiermaggeddon. At least now the official source is maintained by the pre-commit community, which has more experience on how things work for pre-commit.
> Fix prettier installation yet again

- .github/workflows/pre-commit.yml.jinja
- .travis.yml.jinja
- copier.yml
Let's try this ?
This should give a faster feedback build for those who ensure that pre-commit is green before pushing.
And this will test that the merge bot works correctly with GitHub actions.
> Move pre-commit from Travis to GitHub actions

- .pre-commit-config.yaml.jinja
Includes fix for issue when installing docutils dependency.
docutils 0.15.1-post1 has installation issues with pip.
see pypa/pip#9203 (comment)
see https://travis-ci.com/github/OCA/wms/jobs/457408267#L297
> [FIX] Upgrade maintainer-tools

- .pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml
So as not to encourage developers to use str.format() as there are cases where it can introduce security issues.
See https://github.com/OCA/pylint-odoo/issues/302
> [RFR] pre-commit: prevent pyupgrade from replacing printf with str.format()

- version-specific/13.0/.pre-commit-config.yaml
https://github.com/pre-commit/mirrors-prettier/issues/6 affects our repos, as it can be seen on https://github.com/OCA/social/runs/1770760744?check_suite_focus=true#step:4:110 for https://github.com/OCA/social/pull/664 and it produces random results when running `pre-commit` in different environments.
I apply here the workaround explained in that issue.
At the same time, I double-checked that we can run all prettier jobs in a single hook, so I take this chance to apply that logic, and to limit by file extensions, to make it work just like the v14 branch with #48, more predictable and efficent.
> [FIX] prettier for v13 broken in mirror

- .flake8
Fix #52 by adopting the new official recommendation from https://github.com/psf/black/pull/2050. Now the linter and the formatted are configured likewise.
> Increase line length

- .isort.cfg
Add ensure_newline_before_comments, see:
https://black.readthedocs.io/en/stable/compatible_configs.html#configuration
To trigger the rule, add a comment before some import.
> Improve isort compatibility with black

- .flake8
- .pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml
As flake8 > 3.7.0 supports per-file-ignores options, use it directly
in .flake8 configuration file
> [IMP] flake8: Add F401 ignore configuration directly in .flake8

- oca_dependencies.txt
> [FIX] oca_dependencies.txt: typo on anchor id

- .pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml
This should let us rely more on the cleaning power of autoflake. It removes all unused imports (not just from the stdlib), variables and dict keys. Also, it expands star imports (which shouldn't happen usually, but in any case it helps).
> [IMP] autoflake more

- oca_dependencies.txt
The last change (in #57) is causing copier update merge conflicts
on all repos that touched it, essentially preventing a mass update to
the latest template.
Since this file will either go away or be auto generated, it has little value in the template anyway.
> remove oca_dependencies.txt from template

- .eslintrc.yml
Hi,
I like to propose the following change
globals:
..  
owl: readonly
..
In this way it is not necessary anymore to use the following hint in the script
/* global owl */
> propose global owa

- .eslintrc.yml
Odoo support ES6 since 13.0: https://www.odoo.com/documentation/13.0/administration/install/deploy.html#supported-browsers
Option enabled: https://github.com/eslint/eslint/issues/11451#issuecomment-468022530
> [IMP] eslint: Enable globals for ES6

- .github/workflows/stale.yml
Following up on these topics:
- https://github.com/OCA/oca-github-bot/issues/10
- https://github.com/OCA/oca-github-bot/pull/67
I re-open the discussion to include this stale workflow in our repositories.
The configuration proposed is just to start the conversation, I expect it to change with whatever comes up from this thread :)
For reference: `actions/stale` docs: https://github.com/actions/stale
@sbidoul I understand from https://github.com/OCA/oca-github-bot/pull/67#issuecomment-605619867 that you've played with it on the mis-builder repository, however I don't see it active for the current default branch, did something go wrong with it or was it just forgotten?
> [ADD] Automatic PR / Issue stale workflow

- src/.github/workflows/pre-commit.yml.jinja
https://github.com/OCA/product-attribute/runs/4165598273?check_suite_focus=true#step:4:112
```
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/bin/black", line 5, in <module>
from black import patched_main
File "/home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
from typed_ast import ast3, ast27
File "/home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
from typed_ast import _ast3
ImportError: /home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```
Appears to …
> Fix pre-commit errors with black

- src/.pre-commit-config.yaml.jinja
This should make it clearer that changes in README.rst are lost if not
made to the proper readme/*.rst
Info @wt-io-it
> [IMP] run oca-gen-addon-readme in pre-commit

- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
Rename the test workflow to "tests" for a better badge.
Give a different name to Odoo and OCB jobs.
This comes from https://github.com/OCA/oca-addons-repo-template/pull/106#discussion_r784699533.
> Tweak job names

- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
The interpreter is launched with `-e` option, which makes bash fail as soon as one command fails.
The grep command will fail when there's no match. That's a valid use case, and means that there are no unreleased dependencies (or no dependencies).
See https://github.com/OCA/server-brand/runs/5123509581?check_suite_focus=true for a false negative. I attach logs here to be able to consult them after github does its GC: [logs_26.zip](https://github.com/OCA/oca-addons-repo-template/files/8031805/logs_26.zip)
> [FIX] false failures when detecting unreleased dependencies

- src/.github/workflows/pre-commit.yml.jinja
- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
Because of how GitHub workflows works, two jobs were created for every
commit: one for the pull request, and one for the push. This patch
changes that behaviour.
Fixes #129
> [FIX] Do not run CI jobs twice on every commit

- src/.eslintrc.yml
Chosen as [`MAX_ES_VERSION`](https://github.com/odoo/odoo/blob/c16bc3192/odoo/addons/test_lint/tests/test_ecmascript.py#L14) by Odoo since 14.0 [^1]
NOTE: IMO it's not worth adding version-specific templates for this (to keep 2017 version for 13.0), as the list of supported browsers hasn't changed.. it's only that we're all a bit older now
> [IMP] eslint: bump to escmascript 2019

- src/.github/workflows/pre-commit.yml.jinja
- src/.pre-commit-config.yaml.jinja
Fixes https://github.com/OCA/oca-addons-repo-template/issues/127
> [FIX] pylint-odoo: usable under python 3.10

- .pre-commit-config.yaml
- src/.pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml
Fix #133 
- <14.0: pin black click dependency
- \>=14.0: bump black to 22.3.0
> imp: Odoo <14.0: pin black click dependency to <8.1.0 - Odoo >=14.0: bump black to 22.3.0

- src/.github/workflows/pre-commit.yml.jinja
This is necessary for various reason:
- python 2 for Odoo 10
- python 3.6 for the old flake8 used by branches < 13 in MQT compatibilitly mode
- python < 3.9 for the pylint version used on branch 13.0
This fixes a regression for the 13.0 branches introduced in https://github.com/OCA/oca-addons-repo-template/pull/128 (see example failure in https://github.com/OCA/purchase-workflow/pull/1400).
> Cap python version used for pre-commit

- src/.gitignore
The line "lib/" at the .gitignore file is not really good. 
Because this means no directory with the name lib is added. 
As example see this pr https://github.com/OCA/wms/pull/364
At the module shopfloor_mobile_base of repo https://github.com/OCA/wms
there is the directory static/wms/src/lib and this one would be ignored
> Do not ignore lib directory

- .pre-commit-config.yaml
Currently gitlab.com (and therefore https://gitlab.com/pycqa/flake8) is banned to some countries (such as Cuba, due to the US blockade).
So, I think we can change the pre-commit configuration to use the GITHUB flake8 repository instead of the GITLAB one (https://gitlab.com/pycqa/flake8 -> https://github.com/pycqa/ flake8) since that gitlab repository is a mirror of the github one. This way we will have the original repository and also we do not affect anyone from any country in the use of pre-commit with this configuration.
> [IMP] Change pre-commit flake8 URL

- .github/workflows/test.yml
- README.md
- copier.yml
- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
- src/.pre-commit-config.yaml.jinja
- Upgrade all possible pre-commit hooks.
- Use python 3.10 for CI workflows in Odoo 16 (same version as used by Odoo in their runbots)
-  Defines docker images to use to run tests with Odoo/OCB 16.0
> [IMP] support Odoo 16.0

- src/.pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml.jinja
- version-specific/mqt-compat/.pre-commit-config.yaml.jinja
This is safe, and allows more complex external_dependencies_overrides.
Se example in https://github.com/OCA/server-auth/pull/438
> Bump setuptools-odoo version in pre-commit

- src/.pre-commit-config.yaml.jinja
Today, pre-commit on 14.0 branches started to fail:
https://github.com/OCA/account-financial-tools/actions/runs/4301519746/jobs/7498840452
> [FIX] pre-commit: Enforce last version of pre-commit for 14

- copier.yml
- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
Implementing what suggested in
> The best bet is to modify the OCA CI to only use OCB. At the end, there won't be any counterpart, as there are no more Odoo updates, so if right now is green, the only chance to break it is on OCB. And we will gain less energy consumption in the builds.
_Originally posted by @pedrobaeza in https://github.com/odoo/odoo/issues/115782#issuecomment-1474877996_
The issue fixed in the linked PR is blocking many good PRs in `12.0` out there.
Here I allow to choose if tests should be executed in Odoo/OCB.
I don't know how to test this locally so I just wrote what seemed appropriate, any feedback is appreciated.
I tried removing the old `.copier-answers` from a repository and `copier /path/to/oca-addons-repo-template .` but it isn't using the edited template that I …
> Test only supported Odoo versions

- copier.yml
Implementing what suggested in:
> Do we want to set the default value to OCB for Odoo < 13 ?
_Originally posted by @sbidoul in https://github.com/OCA/oca-addons-repo-template/pull/189#discussion_r1150293178_
> Default Flavor

- .github/workflows/lint.yml
- src/.github/workflows/pre-commit.yml.jinja
- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
Fixes deprecated warning on actions/checkout in GitHub actions:
> Detect unreleased dependencies
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For  more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Upgrade actions/checkout to v3

- .github/workflows/test.yml
- src/.pre-commit-config.yaml.jinja
Fixes the problem explained in https://github.com/OCA/report-print-send/pull/328#discussion_r1209478993.
> build(pylint-odoo): bump for v16

- src/.pylintrc-mandatory.jinja
- tests/test_copy.py
Under OCA/pylint-odoo#426, underscores were replaced with dashes for configuration options, when pylint-odoo was bumped in oca-addons-repo-template#198 this change was not taken into account.
I *think* this is the best way to deal with this?
> fix: pylint-odoo v8 configuration options ignored

- .github/workflows/lint.yml
- src/.pre-commit-config.yaml.jinja
Devs sometimes just update the `readme/*.rst` portions, relying in our nice bot that will convert that to a real `README.rst` + `index.html` after merge.
When functional people go test PRs in runboat, the 1st thing they look at is the README. That's OK because there's where the docs should explain what the module is doing.
These 2 situations are good in their own terms, but when you merge both, you get to a problem. You have to either:
- Teach functional people to review the PR code, go to the `readme/` folder and understand the `.rst` syntax and the advanced github diff tooling.
- Teach devs to remember always using the `oca-gen-addon-readme` before pushing the PR, so functionals can review the README in a more human-friendly fashion.
None of these is a good solution. Both add manual and …
> feat: generate addons readme in pre-commit

- src/.gitignore
- src/.gitignore.jinja
Github started yelling about this on pushes:
```
remote: warning: object 65d1b858f5be86bfce970ad2d62f9da069d2dc0e: gitignoreSymlink: .gitignore is a symlink
remote: warning: object 42ebddb6035aab3e90519f5b7399ed21d136accb: gitignoreSymlink: .gitignore is a symlink
remote: warning: object 03fa2ace7a66607d13abf9f1a4ea8467d9c4f86d: gitignoreSymlink: .gitignore is a symlink
remote: warning: object ef8578ca083d6385d8372f72eb3b6003e7fe0444: gitignoreSymlink: .gitignore is a symlink
remote: warning: object f0a868987d1845511053b3f8a96ce54de503edb0: gitignoreSymlink: .gitignore is a symlink
remote: warning: object cb5a03f27c273dac6c052e5b55333aa6596d664b: gitignoreSymlink: .gitignore is a symlink
remote: warning: object dd98cb3fbaaa95349b1516c6f8a2773c2127fb79: gitignoreSymlink: .gitignore is a …
```
> fix: remove .gitignore symlink

- src/.pre-commit-config.yaml.jinja
Before this change, links in the README are always generated as `OCA/repo_slug` despite the user may have answered a different organization to the question
> What's the organization slug? If you are creating https://github.com/OCA/server-tools, then write "OCA" here.
> Generate README for selected Organization

- src/.pre-commit-config.yaml.jinja
I propose to exclude `readme/` fragments from linters.
As long as the `README.rst` generator accepts them and produces valid `.rst` (which is checked upon `ocabot merge`), we should not bother non technical authors with overly strict formatting issues of readme fragments.
> Don't bother non-technical authors with minor formatting issues in readme fragments

- src/.pre-commit-config.yaml.jinja
When adding a field with groups and that also belong to a domain, it is necessary to duplicate the field in the view to avoid an error. This was solved for pylint_odoo 7.0.5, but the template is not updated. So updating the version will prevent similar problems with future v16 works.
References:
https://github.com/OCA/odoo-pre-commit-hooks/issues/10
https://github.com/OCA/oca-addons-repo-template/issues/195
ping @pedrobaeza
> [IMP] Update pre-commit pylint_odoo version

- .github/workflows/lint.yml
- src/.github/workflows/pre-commit.yml.jinja
Recently I had problems with passing pre-commit, since github action started to use Python 3.12
When running pre-commit action on 3.12 you get following errors:
```
autoflake................................................................Failed
- hook id: autoflake
- exit code: 1
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repo7lg_lq3_/py_env-python3/bin/autoflake", line 5, in <module>
from autoflake import main
File "/home/runner/.cache/pre-commit/repo7lg_lq3_/py_env-python3/lib/python3.12/site-packages/autoflake.py", line 32, in <module>
import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils'
```
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call …
```
> [FIX] github pre-commit action: pin python version to 3.11

- src/.pre-commit-config.yaml.jinja
- version-specific/13.0/.pre-commit-config.yaml.jinja
These directories are typically the output of python build tools. The are already ignored in `.gitignore`.
> Ignore build and dist directories in linters

- .flake8
- .github/workflows/lint.yml
- .isort.cfg
- .pre-commit-config.yaml
- pyproject.toml
Simplify the linters of *this project* (not the templatate... yet).
> Simplify linters using ruff

- copier.yml
- src/.pre-commit-config.yaml.jinja
Add a question to generate pyproject.toml files instead of setup.py.
> Add pyproject.toml instead of setup.py

- .github/workflows/test.yml
- copier.yml
- src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
- tests/test_copy.py
Depends on https://github.com/OCA/oca-ci/pull/54
> Add version 17

- src/{% if use_ruff %}.ruff.toml{% endif%}.jinja
It is disabled by default because ruff-format makes a best effort attempt to satisfy it and may fail otherwise.
It should fine to enable it as it was with flake8 (the default is 88).
See https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules for more information.
> Enable ruff line too long check

- src/{% if use_ruff %}.ruff.toml{% endif%}.jinja
Add missing comma causing ruff to fail :
```
ruff failed
Cause: Failed to parse `.ruff.toml`: TOML parse error at line 10, column 5
|
10 |     "I",  # isort
|     ^
invalid array
expected `]`
```
> [FIX] add missing comma

- src/{% if odoo_version <= 14 %}.oca_hooks.cfg{% endif %}
This will about most of the failing updates to 14.0 dotfiles, since the current pre-commit is running new checks not verified on the previous pre-commit version.
Example where this was verified and got a green build:
https://github.com/OCA/product-attribute/pull/1440
cc @etobella @sbidoul @moylop260
> [FIX] Do not apply XML new style checks to 14.0

- src/.pre-commit-config.yaml.jinja
Rational : once https://github.com/OCA/oca-addons-repo-template/pull/240 has been merged, there is a warning when we run ``pre-commit run -a`` in a repo that uses that template.
```
[WARNING] The top-level 'exclude' field is a regex, not a glob -- matching '/*' probably isn't what you want here
```
This commit removes the warning.
CC : original commiters @tuantrantg / reviewers : @pedrobaeza, @yajo, @simahawk, @carmenbianca
> [FIX] prevent a warning message.

- src/.pre-commit-config.yaml.jinja
Hello,
When using v15/v16/v17, It creates .pre-commit-config.yaml with a line break on the first line. 
If you use pre-commit It fails at the first attempt because this line gets removed.
With this change, the file is created correctly
Thank you!
> [FIX] 15/16/17: Removed first line break on pre-commit template

- src/{% if odoo_version > 12 %}.eslintrc.yml{% endif %}.jinja
Odoo officially supports ecmaVersion 2022 from v17: https://github.com/odoo/odoo/blame/9a11717c17b860ec2f1b2e228517c0d3945c474a/addons/web/tooling/_eslintrc.json#L9
Possible fixes:
- Support it globally
- Make an special template for Odoo >= 17
What do you think?
> [FIX] Support ecmaVersion 2022

- .gitignore
It seems that's the package format for MacOS pandoc library:
https://github.com/OCA/credit-control/commit/2e2adf92d15a6b90b7ab15ed61056b85ffb2b3f2
> [IMP] Include .pkg in .gitignore

- src/.pre-commit-config.yaml.jinja
Don't enforce po pretty format that raises if a msgid has the same value as the msgstr. As weblate has those values, it will lead to problems.
Moreover, in some languages, some translations can have the same value as the original language.
@moylop260 @sbidoul 
Related to : https://github.com/OCA/server-env/pull/204
Needed for v18.
> [FIX] oca-check-po: don't check po-pretty-format

- src/.pre-commit-config.yaml.jinja
The configuration file format has changed, andit does work well with pre-commit.
So we keep the previous version for now.
> Revert eslint upgrade

- src/.pre-commit-config.yaml.jinja
Without updating the linter and using `valid-odoo-versions=18.0`, pylint_odoo (mandatory check) passes green but without checking any rules.
pylint-odoo unfortunately doesn't notify the user of 18.0 not being supported in v9.1.2. Support was added in v9.1.3 (https://github.com/OCA/pylint-odoo/compare/v9.1.2...v9.1.3) in PR https://github.com/OCA/pylint-odoo/pull/497
Example with `valid-odoo-versions=18.0` and `pylint-odoo==v1.9.2`:
Working example with `valid-odoo-versions=18.0` and `pylint-odoo==v1.9.3`:
Builds on: https://github.com/OCA/oca-addons-repo-template/pull/272
pylint_odoo's version was also being overridden. This commit fixes that by adding a new v17 section.
> [FIX] pre-commit: update pylint odoo to enable valid-odoo-versions key for v18

- src/{% if enable_checklog_odoo %}checklog-odoo.cfg{% endif %}
to prevent CI to be red for valid PRs, if no test are executed.
Trouble introduced since https://github.com/OCA/oca-addons-repo-template/pull/271 on V18 branch
Impact many PRs, specially when the repos is empty, that occures a lot at the beginning of a new revision (like here, in V18).
for the time being, a lot of PRs are red for no reason,  which slows down the merge process, and results in a poor user experience for new or occasional contributors.
This PR implement the @StefanRijnhart [suggestion](https://github.com/OCA/account-financial-tools/pull/1963#issuecomment-2503249457).
> [FIX] Add checklog-odoo configuration to not fail when there are no tests in the repo

- src/.pre-commit-config.yaml.jinja
Fixes 15.0 branches:
As spotted in 15.0 branch of https://github.com/OCA/stock-logistics-warehouse/tree/15.0
job: https://github.com/OCA/stock-logistics-warehouse/actions/runs/6711504373/job/18239016420
CI on 15.0 PR are red.
autoflake
```
Traceback (most recent call last):
File "/home/bosd/.cache/pre-commit/repop6v3fone/py_env-python3/bin/autoflake", line 5, in <module>
from autoflake import main
File "/home/bosd/.cache/pre-commit/repop6v3fone/py_env-python3/lib/python3.12/site-packages/autoflake.py", line 32, in <module>
import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils'
````
flake8
```
Traceback (most recent call last):
File "/home/bosd/.cache/pre-commit/repo1vkztq8l/py_env-python3/bin/flake8", line 8, in <module>
sys.exit(main())
^^^^^^
File …
```
> [FIX][15.0] branches Update flake8 autoflake

- src/{% if use_ruff %}.ruff.toml{% endif%}.jinja
- Take over this improvement: https://github.com/OCA/odoo-module-migrator/pull/77
- Instead of implementing in odoo-module-migrator (not always installed), do it directly with Ruff pre-commit hook
- As [this rule](https://docs.astral.sh/ruff/rules/super-call-with-parameters/) is taken into account in Ruff, simply applying its fix when with [extend-safe-fixes](https://docs.astral.sh/ruff/settings/#lint_extend-safe-fixes)
> [IMP] consider unsafe fixes for UP008 as safe

- pyproject.toml
- src/.github/workflows/pre-commit.yml.jinja
Current version will be obsolete after 1st of February.
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> Bump version of actions/cache

- src/.pre-commit-config.yaml.jinja
- src/{% if odoo_version >= 18 %}eslint.config.cjs{% endif %}
Fixes
```
22:23  error  'document' is not defined  no-undef
```
in code like
```
const image = document.createElement("img");
```
> [IMP] eslint config: include browser globals such as 'document'

- src/{% if odoo_version >= 18 %}eslint.config.cjs{% endif %}
In >= 18.0 QUnit is added as global https://github.com/odoo/odoo/blob/4b6770ec30bd00213674df2b075c77f33a0e65d9/addons/web/static/src/%40types/libs.d.ts#L5
Added the key on globals to avoid no-undef linter error.
> [IMP] Add QUnit as global in eslint.config for >=18.0

- src/{% if odoo_version >= 18 %}eslint.config.cjs{% endif %}
It was necessary to do it manually on automation_oca to make it work
https://github.com/OCA/automation/pull/25/commits/b55c25a780ddc21bd338c01a583afecec6b2213d#diff-ade92dc557e1c37f3e97d3323edfba82ec5ae154ff4325ddd06962631a5c2666L194
> [IMP] Add test.js on eslint as modules in order to make it work with hoot

- src/.pre-commit-config.yaml.jinja
Why? Because there are a lot of changes that are not reflected properly and may create a mess if different maintainer tools versions are used in OCA bot and repo template.
For example, in one of the commits we rename 'licence' into 'license'. But because pre-commit is pinned to the commit before this change it is renaming it back again and again making the commit history dirty. And although this was not yet spotted in the OCA repos, some other repos using OCA tools are affected.
> [IMP] bump maintainer tools to the latest version

- src/.pre-commit-config.yaml.jinja
Recent commit fixes error, that raises when creating addons directory from template
https://github.com/OCA/maintainer-tools/commit/b89f767503be6ab2b11e4f50a7557cb20066e667
> [FIX] Use latest maintainer-tools for 18.0
