OCA/oca-addons-repo-template

.pre-commit-config.yaml.jinja
version-specific/13.0/.pre-commit-config.yaml

continuation of https://github.com/OCA/maintainer-quality-tools/pull/676
CC @Yajo @sbidoul

IMP: apply autoflake to remove unsed imports

---

CONTRIBUTING.md.jinja
README.md.jinja

Following https://github.com/OCA/oca-addons-repo-template/issues/6#issuecomment-702863233

Mark modifiable zones in README.md and CONTRIBUTING.md

---

.github/workflows/lint.yml
.github/workflows/test.yml

Fixes #18 and it will probably fix a cache problem affecting #17.

Update action versions

---

.github/workflows/test.yml
copier.yml
pytest.ini

- Use poetry action, easier.
- Cache only venv.
- Fix bug in cache key creation.

Update test workflow

---

.pre-commit-config.yaml.jinja

Add oca-fix-manifest-website pre-commit hook

---

.pre-commit-config.yaml.jinja

In the continuity of https://github.com/OCA/oca-addons-repo-template/pull/46

[FIX][14.0] only run prettier xml on .xml files (like 13.0)

---

.github/workflows/stale.yml

Fix https://github.com/OCA/oca-addons-repo-template/issues/67.

[IMP] process old stale issues/PRs first

---

src/.pre-commit-config.yaml.jinja

Reverts OCA/oca-addons-repo-template#90
See https://github.com/OCA/oca-addons-repo-template/pull/90#issuecomment-981115101

Revert "[IMP] run oca-gen-addon-readme in pre-commit"

---

.gitmodules
src/README.md.jinja
tests/test_copy.py

Link to runboat instead of runbot

---

src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja

Add a ci job to detect unmerged requirements

---

copier.yml

Unconditionally remove .t2d.yml

---

copier.yml
src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
src/.pre-commit-config.yaml.jinja
src/.pylintrc-mandatory.jinja
src/README.md.jinja
version-specific/13.0/.pre-commit-config.yaml

Hi.
First thanks for this great template ! 
I began to use it for grap repo. (and also know that Coop It Easy team do the same). 
I so propose 2 extra simple questions, to make more easy to use this template for other organization. (and also a computed question for the website).
@sbidoul : Do you think it's acceptable ? I set OCA values as default.
@carmenbianca : this should avoid to maintain : 
- https://github.com/coopiteasy/oca-addons-repo-template/pull/1/commits/078f8180ac0a0b6e6d6c1697b7fdaca8c79df834
- https://github.com/coopiteasy/oca-addons-repo-template/pull/1/commits/7abc20425732570e5882f6c1b6e9889354df9c06
- https://github.com/coopiteasy/oca-addons-repo-template/pull/1/commits/9b401a0a2094de6fcfd6e790d41e72b7fcf84640
- …

[IMP] make organization configurable

---

README.md

[FIX] Correctly specify supported versions in README

---

src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja

Odoo v16.0 is using jsonb_path_query_array function available from postgresql >= 12.0

[IMP] support Odoo 16.0

---

poetry.lock
pyproject.toml
src/.pre-commit-config.yaml.jinja
version-specific/13.0/.pre-commit-config.yaml.jinja

Apply the same as a48f386b41ff9dbdab7125e3a362b8eaae5b1af6 but for the projects.

[FIX] Update flake8 repo

---

.github/workflows/test.yml
src/.pre-commit-config.yaml.jinja

[IMP] add fail for en.po files

---

version-specific/13.0/.pre-commit-config.yaml.jinja

I noticed, I only did the change for 14, 15 and 16. Applied the same for 13 :disappointed:

[FIX] add en.po error for 13.0

---

copier.yml
src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja

Add copier question to set CI environment variables

---

src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja

Avoid duplicate env section with github_ci_extra_env

---

.pre-commit-config.yaml
src/.pre-commit-config.yaml.jinja

See PyCQA/isort#2077 and PyCQA/isort#2078 which are fixed by this release.
In https://github.com/OCA/l10n-spain/pull/2788 you can see this fixes the build.

[FIX] isort: started breaking the world today

---

tests/test_copy.py

Changes required for proper operation with the latest version of copier 7.0.1
cc @yajo

[UPD] make the template compatible with the latest version of copier

---

.github/workflows/test.yml
version-specific/13.0/.pre-commit-config.yaml.jinja
version-specific/mqt-compat/.pre-commit-config.yaml.jinja

Pin python version for <= 13.0

---

src/.pre-commit-config.yaml.jinja

Fixes https://github.com/OCA/oca-addons-repo-template/issues/206

fix: incremental addon readme generation for v15 and older too

---

src/.pre-commit-config.yaml.jinja

This is to avoid unncessary merge conflicts.
It will be updated by the bot on merge.
supersedes and closes #220 and #222

Preserve the source digest in README.rst

---

src/.pre-commit-config.yaml.jinja

This comment should not appear in the output

Fix template comment

---

src/.pre-commit-config.yaml.jinja

see https://github.com/OCA/pylint-odoo/pull/477
@pedrobaeza @sbidoul could you please review this?

[IMP] upgrade pylint version to 9.0.4 to support Odoo 17.0

---

src/.pre-commit-config.yaml.jinja

To include https://github.com/OCA/maintainer-tools/pull/596

Upgrade maintainer-tools in pre-commit config

---

src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja

Solves:
- https://github.com/OCA/oca-addons-repo-template/issues/250

[IMP] Add codecov v4 question

---

src/.pre-commit-config.yaml.jinja

Upgrade maintainer-tools

---

src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja

Add support for Odoo 19.0 into gh action
